package app;

import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 * Main frame of the simulator
 */
public class MainFrame extends javax.swing.JFrame{
	private static final long serialVersionUID = 1L;
	private StepThread stepThread;
    private PaintPanel paintPanel;
    
    public MainFrame() {
        // Init auto generated components
        initComponents();
        
        // Load frame position, size and state from the saved settings
        setBounds(Settings.getInt("left",0),Settings.getInt("top",0),Settings.getInt("width",1200),Settings.getInt("height",800));
        if (Settings.getInt("maximized",0) == 1) {
            setExtendedState(getExtendedState() | Frame.MAXIMIZED_BOTH);
        }
        
        // Move focus to the first button to avoid keyboard control from chaning the jSpinner1 value
        jButton1ActionPerformed(null);
        jButton1.requestFocus();
        
        // Load agent count and simulation speed
        jSpinner1.setValue(Settings.getInt("agent_count",1));
        jSlider1.setValue(Settings.getInt("speed",20));
         
        // Window listener to detect window close event
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                // Determine if the window is maximized
                if ((getExtendedState() & Frame.MAXIMIZED_BOTH) == 0) {
                    Settings.setInt("maximized", 0);
                } else {
                    Settings.setInt("maximized", 1);
                }
                
                // Save window position and size after unmaximizing it
                setExtendedState(0);                
                Settings.setInt("top", getY());
                Settings.setInt("left", getX());
                Settings.setInt("width", getWidth());
                Settings.setInt("height", getHeight());
            }
        });
  
        // Create and start autostep thread
        stepThread = new StepThread();
        stepThread.start();

    }
    
    public void refresh() {
        // Repaint cells and world objects
        paintPanel.repaint();
        
        // Calculate and display score
        int score = 0; //RescueFramework.map.getScore();
        int maxScore = 100; //RescueFramework.map.getMaxScore();
        String label = "Time: "+App.map.GetTime()+" | Saved: "+score+" / "+maxScore;
        if (maxScore > 0) {
            label = label +" ("+(score*100/maxScore)+"%)";
        }
        jLabel2.setText(label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        paintPanel = new app.PaintPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rakt�rPakol�s");
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setSize(new java.awt.Dimension(1200, 800));

        jPanel1.setPreferredSize(new java.awt.Dimension(924, 33));

        jButton1.setText("Load simulation");
        jButton1.setFocusCycleRoot(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("No score yet.");

        jButton3.setText("Single step");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Autostep");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jSlider1.setToolTipText("");
        jSlider1.setValue(20);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.setFocusable(false);

        jLabel3.setText("Robots:");
        
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 6));
        jSpinner2.setFocusable(false);
        jSpinner2.setValue(15);

        jLabel5.setText("Width:");
        
        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 6));
        jSpinner3.setFocusable(false);
        jSpinner3.setValue(13);

        jLabel6.setText("Height:");

        jLabel4.setText("Autostep speed:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2))
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton1)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jButton3)
                        .addComponent(jLabel4)))
                .addGap(13, 13, 13))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(paintPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The user clicks the Load map button
     * 
     * @param evt   The click event
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Save selected map and agent count
        //String map = jComboBox1.getSelectedItem()+"";
        int agentCount = (Integer)jSpinner1.getValue();
        int w = (Integer)jSpinner2.getValue();
        int h = (Integer)jSpinner3.getValue();
        //Settings.setString("map", map);
        Settings.setInt("agent_count", agentCount);
        
        // Load the map 
        App.map.Set(h, w, 5, 2, agentCount);
        App.finished = false;
        
        App.env.startAuction(agentCount);
        
        // Update the GUI and disable autostep
        jButton4.setText("Start");
        
        jButton4.setEnabled(false);
        jButton3.setEnabled(false);
        
        
        if (stepThread != null) stepThread.disable();
        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * The user clicks the single step button
     * 
     * @param evt   The click event
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Make one time step
        if (!App.finished) {
	    	boolean ret = App.map.Step();
	        if (!ret) 
	        	App.finished = true;
        }
 
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * The pause / resume button is clicked
     * 
     * @param evt   The click event
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (stepThread.isEnabled()) {
            pause();
        } else {
            resume();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * The speed bar is being moved
     * 
     * @param evt   The change event
     */
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        if (stepThread != null) {
            // Update the simulation speed of the stepThread
            stepThread.setStepTime(getSimulationSpeed());
            // Save speed settings
            Settings.setInt("speed", jSlider1.getValue());
        }
    }//GEN-LAST:event_jSlider1StateChanged

    /**
     * Pause the autostep thread
     */
    public void pause() {
        stepThread.disable();
        jButton4.setText("Autostep");
    }
    
    /**
     * Resume the paused autostep thread
     */
    public void resume() {
        stepThread.enable();
        jButton4.setText("Pause");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1; 	//loadmap
    private javax.swing.JButton jButton3; 	// single step
    private javax.swing.JButton jButton4; 	//reset/resume
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;		//Robots
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;		//With
    private javax.swing.JLabel jLabel6;		//Height
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;	//speed
    private javax.swing.JSpinner jSpinner1;	//�gens sz�m
    private javax.swing.JSpinner jSpinner2;	//sz�less�g
    private javax.swing.JSpinner jSpinner3;	//magass�g
    // End of variables declaration//GEN-END:variables

 
    /**
     * Determine simulation speed based on the jSlider1 settings
     * @return     The 3-103 sleep time for the StepThread
     */
    public int getSimulationSpeed() {
        return (100-jSlider1.getValue())+3;
    }
    
    public void enableStart() {
    	jButton4.setEnabled(true);
        jButton3.setEnabled(true);
    }
}
